TEMP_FOLDER = ".robot-test-balancer"

PARAMETER_DRY_RUN = "--dryrun"
PARAMETER_DISABLE_LOG = ["-l", "NONE"]
PARAMETER_DISABLE_HTML = ["-r", "NONE"]
PARAMETER_ENABLE_OUTPUT_TO_DEFAULT = ["-o", "output.xml"]
PARAMETER_OUTPUT_DIR_TEMP = ["-d", TEMP_FOLDER]
ROBOT_FRAMEWORK_DATETIME_FORMAT = "%Y%m%d %H:%M:%S.%f"
